steps:
  - id: "Build application"
    name: "golang"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go mod tidy
        env GOOS=linux GOARCH=amd64 go build -o=/workspace/nwc-trading-server .
