steps:
  - id: "Build application"
    name: "golang"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> id_rsa
        chmod 400 id_rsa
        git config --add --global core.sshCommand 'ssh -i /workspace/id_rsa'
        git config --global url.ssh://git@github.com/.insteadOf https://github.com/
        go get
        make ciBuild
    secretEnv:
      [
        "DB_CONNECTSTRING",
        "EXTRA_KEY_STRING",
        "HASH_COST",
        "GOPRIVATE",
        "SSH_KEY",
      ]
  - id: "Copy onto Box and Restart"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        gcloud compute ssh alicolliar@trade-api-server --command="sudo systemctl stop trade-api" --zone="us-central1-a"
        gcloud compute scp /workspace/nwc-trading-server alicolliar@trade-api-server:~ --zone="us-central1-a"
        gcloud compute ssh alicolliar@trade-api-server --command="sudo systemctl start trade-api" --zone="us-central1-a"

options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true

availableSecrets:
  secretManager:
    - versionName: projects/335883769512/secrets/DB_CONNECTSTRING/versions/1
      env: "DB_CONNECTSTRING"
    - versionName: projects/335883769512/secrets/EXTRA_KEY_STRING/versions/1
      env: "EXTRA_KEY_STRING"
    - versionName: projects/335883769512/secrets/HASH_COST/versions/2
      env: "HASH_COST"
    - versionName: projects/335883769512/secrets/GOPRIVATE/versions/1
      env: "GOPRIVATE"
    - versionName: projects/335883769512/secrets/SSH-KEY/versions/2
      env: "SSH_KEY"
